### ISSUE TITLE
有个问题想问一下

### ISSUE THREAD

**Issue by simplecxm** [lhw666/gitTest#1]
为啥上传这么多没有用的文件呢？ @lhw666

**Comment by lhw666** [comment]
你以为人人都像你这么优秀？

**Comment by lhw666** [comment]
你以为人人像你这么优秀？






在 2019-03-01 17:16:11，"Simple4H" <notifications@github.com> 写道：


为啥上传这么多没有用的文件呢？ @lhw666

**Comment by simplecxm** [comment]
> 你以为人人像你这么优秀？ 在 2019-03-01 17:16:11，"Simple4H" <notifications@github.com> 写道： 为啥上传这么多没有用的文件呢？ @lhw666 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
